### Авторизация
POST http://localhost:8000/auth/jwt/create
Content-Type: application/json

{
    "username": "jeff@amazon.com",
    "password": "123"
}

### Информация об аккаунте
GET http://localhost:8000/accounts
Authorization: Bearer <token>

{
    "username": "jeff@amazon.com",
    "password": "123"
}