### Авторизация
# @name login
POST http://localhost:8000/auth/jwt/create
Content-Type: application/json

{
    "username": "jeff@amazon.com",
    "password": "123"
}

###

@token = {{login.response.body.$.access}}

### Информация об аккаунте
GET http://localhost:8000/accounts
Authorization: Bearer {{token}}

### Информация об ордерах
GET http://localhost:8000/orders
Authorization: Bearer {{token}}

### Новый ордер
POST http://localhost:8000/orders/
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "sell_currency": "RUB",
    "amount": "15.00",
    "buy_currency": "USD",
    "price": "30.00"
}